# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

pipelines:
  default:
    - step:
        script:
          - apt-get install software-properties-common -y
          - apt-add-repository ppa:ansible/ansible
          - apt-get update
          - apt-get install ansible -y
          - chmod 0400 ops/playbooks/keys/kp_dev.pem
          - ansible-playbook -v ops/playbooks/main/setup.yml -i ops/playbooks/inventories/dev
